- hosts: openbmp
  vars:
        - code_dir: "~/git" # location to install docker files and git repo
        - OBMP_DATA_ROOT: "/var/openbmp" # root of the openbmp data
        - docker_users: ['openbmp']


  tasks:


    - name: Confirm important file deletion
      pause:
              prompt: "  This playbook will remove all data from a previous openbmp data created in {{ OBMP_DATA_ROOT }} \n  and remove all existing docker containers, and prepare for a new 2.0.3+ install.\n   https://www.openbmp.org/release_notes/2.0.3.html\n   Do you want to continue? [yes/no]"
      register: confirm_delete

    - name: Confirm you have a backup config
      pause:
              prompt: "   Did you backup everything you need last chance [yes/no]"
      register: confirm_backup

    - name: stop the play
      fail:
              msg: "Halting the playbook"
      when: confirm_backup.user_input != "yes"



    - name: backup existing docker-compose.yml if there is a file there
      ansible.builtin.copy:
          src: "{{ code_dir }}/docker-compose.yml"
          dest: "{{ code_dir }}/docker-compose.yml.pre_2.0.3"
          remote_src: yes

    - name: "shutdwn and remove the existing containers, https://www.openbmp.org/release_notes/2.0.3.html"
      ansible.builtin.shell: 
          cmd: "OBMP_DATA_ROOT={{OBMP_DATA_ROOT}} docker-compose -f ./docker-compose.yml -p obmp down"
          chdir: "{{ code_dir }}"


    - name: "remove the the /config/do_not_init_db file so the DB and be rebuilt"
      become: true
      become_user: root
      ansible.builtin.file:
         state: absent
         path: "{{ OBMP_DATA_ROOT}}/config/do_not_init_db"


    - name: "remove old postgress data"
      become: true
      become_user: root
      ansible.builtin.shell: 
          cmd: "rm -rf {{ OBMP_DATA_ROOT}}/postgres/data/*"
          chdir: "{{ OBMP_DATA_ROOT }}"


    - name: "remove old postgress data"
      become: true
      become_user: root
      ansible.builtin.shell: 
          cmd: "rm -rf {{ OBMP_DATA_ROOT}}/postgres/ts/*"
          chdir: "{{ OBMP_DATA_ROOT }}"

    - name: "remove old kafka data"
      become: true
      become_user: root
      ansible.builtin.shell:
          cmd:  "rm -rf {{ OBMP_DATA_ROOT}}/kafka-data/*"
          chdir: "{{ OBMP_DATA_ROOT }}"

    - name: "remove old zookeeper data"
      become: true
      become_user: root
      ansible.builtin.shell:
          cmd:  "rm -rf {{ OBMP_DATA_ROOT}}/zk-data/*"
          chdir: "{{ OBMP_DATA_ROOT }}"

    - name: "remove old zookeeper log"
      become: true
      become_user: root
      ansible.builtin.shell:
          cmd: "rm -rf {{ OBMP_DATA_ROOT}}/zk-log/*"
          chdir: "{{ OBMP_DATA_ROOT }}"


    - name: "remove old grafana grafana/dashboards/"
      become: true
      become_user: root
      ansible.builtin.shell:
          cmd:  "rm -rf {{ OBMP_DATA_ROOT}}/grafana/dashboards/"
          chdir: "{{ OBMP_DATA_ROOT }}"


    - name: "remove old grafana grafana/plugins"
      become: true
      become_user: root
      ansible.builtin.shell:
          cmd:  "rm -rf {{ OBMP_DATA_ROOT}}/grafana/plugins"
          chdir: "{{ OBMP_DATA_ROOT }}"

    - name: "remove old grafana grafana/alerting"
      become: true
      become_user: root
      ansible.builtin.shell: 
          cmd: "rm -rf {{ OBMP_DATA_ROOT}}/grafana/alerting"
          chdir: "{{ OBMP_DATA_ROOT }}"

    - name: "remove old grafana grafana/provisioning/"
      become: true
      become_user: root
      ansible.builtin.shell: 
          cmd: "rm -rf {{ OBMP_DATA_ROOT}}/grafana/provisioning/"
          chdir: "{{ OBMP_DATA_ROOT }}"

    - name: "remove old grafana grafana/grafana.db"
      become: true
      become_user: root
      ansible.builtin.shell:
          cmd:  "rm -rf {{ OBMP_DATA_ROOT}}/grafana/grafana.db"
          chdir: "{{ OBMP_DATA_ROOT }}"

    - name: "steps 2-4 https://www.openbmp.org/getting_started.html"
      import_role:
          name: openbmp
      tags: openbmp

    - name: "Update the new docker-compose.yml file with your settings, and then re-run with --tags=newdbuild"
      debug:
          msg: "copy the {{code_dir}}/docker-compose_current.yml to docker-compose.yml, and edit as needed.  Once you are ready, re-run this play with the --tags=newbuild to rebuild\n ansible-playbook -K -i hosts upgrade-pre_2.0.3.yml --tags=newbuild"


    - name: "build the containers"
      shell:
         cmd: "OBMP_DATA_ROOT={{OBMP_DATA_ROOT}} docker-compose -f ./docker-compose.yml -p obmp up -d"
         chdir: "{{ code_dir }}"
      tags: [never, newbuild]



